### ISSUE TITLE
Update to Angular 15

### ISSUE THREAD

**Issue by pavandixit93** [HyperviewHQ/angular2gridster#4]
Hi @HyperviewHQ, @ramijebara, @cklogs Do you have any plan to update this to Angular 15? Or Is it fine if we create angular 15 upgrade PR if you don't have any early plan?

**Comment by ramijebara** [comment]
hi @pavandixit93 , thank you for the offer! 
We are planning to port it to Angular 15 as we port our dependent projects to Angular 15 in the next couple months but if you need it sooner, I am happy to review a PR if you send one. 
Thank you!

**Comment by pavandixit93** [comment]
> 



> hi @pavandixit93 , thank you for the offer! We are planning to port it to Angular 15 as we port our dependent projects to Angular 15 in the next couple months but if you need it sooner, I am happy to review a PR if you send one. Thank you!

Hi @ramijebara 
Ok, Understood. Sure, I would like to try this, I will try to do it may be in next week.

**Comment by pavandixit93** [comment]
Hi @ramijebara 
I have updated to angular v15 using angular schematics and migration guide. Kindly have review here - 
https://github.com/HyperviewHQ/angular2gridster/pull/6
Thank you.

**Comment by ramijebara** [comment]
PR is merged/work is completed
